uniform_title_tesim: 'Uniform Title'
series_title_tesim: 'Series Title'
parent_title_tesim: 'Title of Parent Work'
creator_tesim: 'Creator'
contributors_tesim: 'Contributor'
date_created_tesim: 'Date Created'
date_issued_tesim: 'Date Issued'
data_collection_dates_tesim: 'Data Collection Dates'
human_readable_content_type_tesim: 'Content Type'
content_genres_tesim: 'Genre'
extent_tesim: 'Extent/Dimensions'
primary_language_tesim: 'Primary Language'
notes_tesim: 'Note'
abstract_tesim: 'Description/Abstract'
table_of_contents_tesim: 'Table of Contents'
